core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('coresite.urls')),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('carts/', include('carts.urls')),
    path('payment/', include('billings.urls')),
    path('mycourses/', include('enrolls.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', include('customadmin.urls')),
    path('quiz/', include('quizapp.urls')),
    path('superadmin/', admin.site.urls),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'coresite.views.handler404'
handler500 = 'coresite.views.handler500'

admin.site.site_header = "GainSkill Super Admin"
admin.site.site_title = "GainSkill"
admin.site.index_title = "Welcome to GainSkill"

dashboard/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import DashboardView, MyEnrolledCourseListView, StartCourseView, InstructorCourseListView



app_name = "dashboard"

urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('my-courses/', InstructorCourseListView.as_view(), name="instructor-courses"),
    path('enrolled-courses/', MyEnrolledCourseListView.as_view(), name="my-courses"),
    path('classroom/<slug:slug>/', StartCourseView.as_view(), name="start-course"),
]

quizapp/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import AddQuiz, AddQuizQuestion, Exam, save_ans ,result,clr, certificate

app_name = "quiz"
urlpatterns = [
    path('add/<int:id>/', AddQuiz, name="add_quiz"),
    path('add/question/<int:id>/', AddQuizQuestion, name="add_quiz_question"),
    path('course/quiz/<int:id>/', Exam, name="exam"),
    path('save_ans/', save_ans, name="save_ans"),
    path('result/<int:id>/', result, name="quiz_result"),
    path('certificate/<int:id>/', certificate, name="certificate"),
    # path('result/', result, name="quiz_result"),
    path('clr/', clr, name="clr"),

]

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.http import Http404

from enrolls.models import EnrollCouese
from courses.models import *
from courses.decorators import user_is_instructor, user_is_student


from django.views.decorators.clickjacking import xframe_options_exempt


class DashboardView(View):
    
    template_name = 'mainsite/site/dashboard.html'


    def get(self, request, *args, **kwargs):
        total_course = None
        if request.user.role == 'tea':
            total_course = Course.objects.filter(instructor = self.request.user).count()
            
        elif request.user.role == 'stu':
            
            total_course = EnrollCouese.objects.filter(user = self.request.user).values('products').count()
        context = {
            'total_course':total_course
        }
        return render(request, self.template_name, context)   

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name)    


class InstructorCourseListView(ListView):
    model = Course
    context_object_name = 'mycourses'
    template_name = "mainsite/site/instructor-courses.html"

    @method_decorator(login_required)
    @method_decorator(user_is_instructor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        return self.model.objects.filter(instructor = self.request.user)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total'] = self.get_queryset().count()

        return context


class MyEnrolledCourseListView(ListView):
    model = EnrollCouese
    context_object_name = 'mycourses'
    template_name = "mainsite/site/my-courses.html"

    @method_decorator(login_required)
    @method_decorator(user_is_student)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    

    def get_queryset(self):
        return self.model.objects.filter(user = self.request.user).first()

    


class StartCourseView(DetailView):

    model= Course
    context_object_name = 'course'
    template_name = 'mainsite/site/classroom.html'

    @method_decorator(login_required)
    @method_decorator(xframe_options_exempt)
    
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
        
    def get_object(self, queryset=None):
        obj = super(StartCourseView, self).get_object(queryset=queryset)
        
        if obj is not None:
            enrolledOrnot = get_object_or_404(EnrollCouese, user = self.request.user, products = obj)
            return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()

        except Http404:
            raise Http404("Course doesn't exists")
        context = self.get_context_data(object=self.object)
        vvid = Lesson.objects.filter(course=context['object'].id).values('video_link').all()

        # print(vvid)
        topic_category_dic =[]
        for vlink in vvid:
            # for topic in LessonContent.objects.filter(id=vlink['video_link']):
                # print(topic)

            for topic in LessonContent.objects.filter(id=vlink['video_link']):
                # print( 'Link', topic.video_link, 'Text' , topic.text_content)
                topic_category_dic.append(topic)
                
            
        context['topic_category'] = topic_category_dic

        return self.render_to_response(context)

templates/mainsite/site/classroom.html
{% extends 'mainsite/base.html' %}
{% load static %}
{% load youtube_link_replace %}

{% block content %}
<!-- Start Page Title Area -->
<div class="page-title">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <h3>{{ course.title }}</h3>
            </div>
        </div>
    </div>
</div>
<!-- End Page Title Area -->

<!-- Start Course Details Area -->
<section class="course-details-area ptb-100">
    <div class="container-fluid">
        
        <div class="row  px-0 mx-0">
            <!-- {% for lesson in course.course.all %} -->
            <div class="col-lg-4 pr-0 mr-3">
               <div class="card">
                    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        {% for tcontent in topic_category %}
                        <a onclick="reload({{ tcontent.id }});" class="nav-link {% if forloop.first %}  active {% endif %} " id="v-pills-{{ tcontent.id }}-tab" data-toggle="pill" href="#v-pills-{{ tcontent.id }}" role="tab" aria-controls="v-pills-home" aria-selected="true">
                            <i class="icofont-ui-play pr-2"></i>Lecture {{ forloop.counter }}
                            <span class="ls-title "> {{ tcontent.title }}</span>
                                 50 min
                            </span>
                        </a>
                        {% endfor %}
                        {% for quiz in course.courseref.all %}
                        <a href="{% url 'quiz:exam' quiz.id  %}" class="nav-link ">
                            <i class="icofont-ui-play pr-2"></i>
                            <span class="ls-title "> 
                                    Participate Quiz
                            </span>
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-lg-6 pl-0 ml-0">
            <div class="tab-content" id="v-pills-tabContent">
                {% for tcontent in topic_category %}
                    <div class="tab-pane fade {% if forloop.first %} show active{% endif %}" id="v-pills-{{ tcontent.id }}" role="tabpanel" aria-labelledby="v-pills-{{ tcontent.id }}-tab">
                        {% if tcontent.video_link %}
                        {% youtube_link_replace tcontent as videourl %}
                        
                        <div class="videoWrapper">
                            {% if videourl %}
                            
                            <iframe id="iframeid" width="920" height="500" type="text/html" src="{% youtube_link_replace tcontent  %}" frameborder="0" allow="accelerometer;  clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            {% else %}
                            <iframe id="iframeid" width="920" height="500" type="text/html" src="{{ tcontent.video_link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            {% endif %}
                        </div>
                        {% endif %}
                    {% if tcontent.text_content != none %}
                    <div class="course-details-tabs ml-5">
                        {{ tcontent.text_content }}
                    </div>
                    {% endif %}
                  </div>
                {% endfor %}
            </div>
            </div>
            <!-- {% endfor %} -->
        </div>
    </div>
</section>
<script> 
    function reload(id) { 
        console.log(id);
        document.getElementById('iframeid').src += id;
    } 
    
</script> 
{% endblock %}

templates/mainsite/site/dashboard.html
{% extends 'mainsite/base.html' %}
{% load static %}
{% load ratings %}

{% block content %}
        

        
        <!-- Start Page Title Area -->
        <div class="page-">
            <div class="d-table">
                <div class="d-table-cell">
                    <div class="container-fluid mx-2">
                        <div class="student-dashboard__banner mx-4">
                            <div class="student-dashboard__container mx-5">
                                <p class="student-dashboard__welcome px-5 mx-5">Welcome Back, {{ request.user.get_full_name }} !</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
        <!-- End Page Title Area -->
        
        <!-- Start Courses Area -->
        <section class="courses-area ptb-100">
            <div class="container">
                <div class="row"> 
            {% if request.user.role == 'stu' %}
            <div class="col-lg-6 col-md-6">
                    <a href="{% url 'dashboard:my-courses' %}">
                        <div class="course-details-single d-flex">
                        <div class="course-details-icon"><i class="fas fa-money-check-alt" aria-hidden="true"></i></div>
                        <div class="course-details-content">
                            <h5 class="item-top-title">Total Enrolled Courses</h5>
                            <h6 class="course-item-title">{{ total_course }}</h6>
                        </div>
                        </div>
                    </a>
                    </div>
         


                    <!-- <div class="col-lg-6 col-md-6">
                        <div class="course-details-single d-flex">
                        <div class="course-details-icon"><i class="fas fa-money-check-alt" aria-hidden="true"></i></div>
                        <div class="course-details-content">
                            <span class="item-top-title">Total Balance</span>
                            <h6 class="course-item-title">$0</h6>
                        </div>
                        </div>
                    </div> -->


              

                    {% elif request.user.role == 'tea' %}
                    <div class="col-lg-6 col-md-6">
                        <a href="{% url 'dashboard:instructor-courses' %}">
                            <div class="course-details-single d-flex">
                            <div class="course-details-icon"><i class="fas fa-money-check-alt" aria-hidden="true"></i></div>
                            <div class="course-details-content">
                                <h5 class="item-top-title">Total Courses</h5>
                                <h6 class="pt-3">{{ total_course }}</h6>
                            </div>
                            </div>
                        </a>
                        </div>
       
    
    
                        <div class="col-lg-6 col-md-6">
                            <div class="course-details-single d-flex">
                            <div class="course-details-icon"><i class="fas fa-money-check-alt" aria-hidden="true"></i></div>
                            <div class="course-details-content">
                                <h5 class="item-top-title">Total Balance</h5>
                                <h6 class="pt-3">$0</h6>
                            </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </section>
        <!-- End Courses Area -->
        
{% endblock %}

templates/mainsite/site/instructor-courses.html
{% extends 'mainsite/base.html' %}
{% load static %}
{% load ratings %}

{% block content %}



<!-- Start Page Title Area -->
<div class="page-">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container-fluid mx-2">
                <div class="student-dashboard__banner mx-4">
                    <div class="student-dashboard__container mx-5">
                        <p class="student-dashboard__welcome px-5 mx-5">Welcome Back, {{ request.user.get_full_name }} !
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- End Page Title Area -->
<!-- Start Courses Area -->
<section class="courses-area m-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 pl-0 mb-5">
                <h3>Total Courses : {{ total }} </h3>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Course Name</th>
                        <th>Published / Pending</th>
                        <th>Quiz</th>
                    </tr>
                </thead>
                <tbody>
                    {% for course in mycourses %}
                    <tr>
                        <td><a href="{{ course.get_absolute_url }}">{{ course.title }}</a></td>
                        <td>{% if course.is_published == True %}
                                Published
                            {% else %}
                                Pending
                            {% endif %}
                        </td>
                        {% if course.courseref.all %} 
                        <td>Assined</td>
                        {% else %}
                        <td><a href="{% url 'quiz:add_quiz' course.id  %}">Assign Quiz</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
<!-- End Courses Area -->

{% endblock %}

templates/mainsite/site/my-courses.html
{% extends 'mainsite/base.html' %}
{% load static %}
{% load ratings %}

{% block content %}
        

        
        <!-- Start Page Title Area -->
        <div class="page-">
            <div class="d-table">
                <div class="d-table-cell">
                    <div class="container-fluid mx-2">
                        <div class="student-dashboard__banner mx-4">
                            <div class="student-dashboard__container mx-5">
                                <p class="student-dashboard__welcome px-5 mx-5">Welcome Back, {{ request.user.get_full_name }} !</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
        <!-- End Page Title Area -->
        
        <!-- Start Courses Area -->
        <section class="courses-area ptb-100">
            <div class="container">
                <div class="row"> 
                {% for course in mycourses.products.all %}
                    <div class="col-lg-4 col-md-6">
                        <div class="single-courses-item">
                            <div class="courses-img">
                                <img src="{{ course.thumbnail.url }}" alt="course" />
                            </div>
                            
                            <div class="courses-content">
                                <h3><a href="{{ course.get_absolute_url }}">{{ course.title}}</a></h3>
                            </div>
                            
                            <div class="courses-content-bottom">
                                <h4 class="cart-buttons">                               
                                    <a href="{% url 'dashboard:start-course' course.slug %}" class=""><button class="btn btn-danger">START COURSE</button></a>

                                </h4>
 

                            </div>
                        </div>
                    </div>
                    {% endfor %}


                    <div class="col-lg-12 col-md-12">
                        <div class="pagination-area">
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">
                                    <li class="page-item">
                                        <a class="page-link" href="#" aria-label="Previous">
                                            <i class="icofont-stylish-left"></i>
                                        </a>
                                    </li>
                                    
                                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                    
                                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                                    
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    
                                    <li class="page-item">
                                        <a class="page-link" href="#" aria-label="Next">
                                            <i class="icofont-stylish-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Courses Area -->
        
{% endblock %}