core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('coresite.urls')),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('carts/', include('carts.urls')),
    path('payment/', include('billings.urls')),
    path('mycourses/', include('enrolls.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', include('customadmin.urls')),
    path('quiz/', include('quizapp.urls')),
    path('superadmin/', admin.site.urls),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'coresite.views.handler404'
handler500 = 'coresite.views.handler500'

admin.site.site_header = "GainSkill Super Admin"
admin.site.site_title = "GainSkill"
admin.site.index_title = "Welcome to GainSkill"

quizapp/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import AddQuiz, AddQuizQuestion, Exam, save_ans ,result,clr, certificate

app_name = "quiz"
urlpatterns = [
    path('add/<int:id>/', AddQuiz, name="add_quiz"),
    path('add/question/<int:id>/', AddQuizQuestion, name="add_quiz_question"),
    path('course/quiz/<int:id>/', Exam, name="exam"),
    path('save_ans/', save_ans, name="save_ans"),
    path('result/<int:id>/', result, name="quiz_result"),
    path('certificate/<int:id>/', certificate, name="certificate"),
    # path('result/', result, name="quiz_result"),
    path('clr/', clr, name="clr"),

]

carts/models.py
from decimal import Decimal
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed


from courses.models import Course


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if cart_obj.user is None and request.user.is_authenticated:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            try:
                cart_obj = Cart.objects.create(user=request.user)
            except:
                cart_obj = Cart.objects.create(user=None)

            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj



class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.DO_NOTHING)
    products    = models.ManyToManyField(Course, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=65, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=65, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for product in products:
            if product.price is not None or product.offer_price is not None:
                if product.offer_price:
                    total += product.offer_price
                else:
                    total += product.price
                
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) #* Decimal(1) # 8% tax
    else:
        instance.total = 0.00
pre_save.connect(pre_save_cart_receiver, sender=Cart)

 

templates/mainsite/quiz/add_quiz.html
{% extends 'mainsite/base.html' %}
{% load static %}

{% block content %}
<!-- Start Page Title Area -->
<div class="page-title">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <h3>Add New Quiz</h3>
            </div>
        </div>
    </div>
</div>


<!-- Start Register Area -->
<section class="register-area ptb-100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
                <div class=" p-5 m-5">
                    <div class="panel-body"> 
                        <div class="col-lg-12 col-md-12">
                            <div class="apply-form">
                                <h3>Add Quiz</h3>
                                <form method="POST" action="">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 px-5">
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <div class="form-group">
                                                    <label for="id_descriptions">Quiz Descriptions:</label>
                                                    <input type="text" class="form-control" name="descriptions"
                                                    id="id_descriptions" placeholder="Descriptions">
                                                </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12">
                                                <button class="btn btn-primary" type="submit">ADD</button>
                                            </div>
                                        </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- End Register Area -->

    {% endblock %}
{% block script %}
 
{% endblock %}

templates/mainsite/quiz/add_quiz_question.html
{% extends 'mainsite/base.html' %}
{% load static %}

{% block content %}
<!-- Start Page Title Area -->
<div class="page-title">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <h3>Add New Course</h3>
            </div>
        </div>
    </div>
</div>

<!-- Start Register Area -->
<section class="register-area ptb-100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
                <div class=" p-5 m-5">
                    <div class="panel-body"> 
                        <div class="col-lg-12 col-md-12">
                            <div class="apply-form">
                                <h3>Add Quiz Question</h3>
                                <form method="POST" id="post-submit-ajax" action="{% url 'quiz:add_quiz_question' quiz.id %} ">

                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 px-5">
                                                
                                                <input type="hidden" name="quiz"
                                                    id="id_quiz" value="{{ quiz.id }}">
                                            
                                            
                                      
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="question"
                                                    id="id_question" placeholder="Question">
                                                </div>
                                            </div>
                                       
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <div class="form-group">
                                                    <input type="file" class="form-control" name="image"
                                                    id="id_image" placeholder="">
                                                </div>
                                            </div>
                                           
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="choice_one"
                                                    id="id_choice_one" placeholder="Option One">
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="choice_two"
                                                    id="id_choice_two" placeholder="Option Two">
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="choice_three"
                                                    id="id_choice_three" placeholder="Option Three">
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="choice_four"
                                                    id="id_choice_four" placeholder="Option Four">
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12 px-5">
                                                <!-- <label class="labelc" for="category">Category</label> -->
                                                <select name="ans" required="" id="id_ans" class="form-control">

                                                    <option selected disabled>Correct Ans</option>
                                                    
                                                    <option value="choice_one">Option One</option>
                
                                                    
                                                    <option value="choice_two">Option Two</option>
                
                                                    
                                                    <option value="choice_three">Option Three</option>
                
                                                    
                                                    <option value="choice_four">Option Four</option>
                
                                                    
                                                </select>
                                            </div>
                                            <div class="col-lg-12 col-md-12">
                                                <button class="btn btn-primary" type="submit">ADD</button>
                                            </div>
                                        </div>
                                
        
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- End Register Area -->

    {% endblock %}
{% block script %}
 
{% endblock %}

templates/mainsite/quiz/quiz_exam copy.html
{% extends 'mainsite/base.html' %}
{% load static %}

{% block content %}
<!-- Start Page Title Area -->
<div class="page-title">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <h3>QUIZ</h3>
            </div>
        </div>
    </div>
</div>
    <div class="mt-5 text-center"><h1>Question {{ questions.end_index }} of  {{count}}</h1></div>
    <div class="col-lg-8 border border-success p-4 m-4 mx-auto">
                {% for i in questions%}
                <h1 class="text-center m-4">{{i.question}}</h1>
                <form>
                    <div class="radio">
                    <label><input class="mr-3" type="radio" name="name"  id="option1" value="choice_one">{{i.choice_one}} </label> 
                    </div>
                    <div class="radio">
                    <label > <input class="mr-3" type="radio" name="name"  id="option2" value="choice_two">{{i.choice_two}}</label>
                  </div>
                  <div class="radio">
                    <label ><input class="mr-3" type="radio" name="name" id="option3" value="choice_three">{{i.choice_three}}</label>
                  </div>
                    <div class="radio">
                    <label ><input class="mr-3" type="radio" name="name"  id="option4" value="choice_four">{{i.choice_four}} </label>
                </div>
            </form>
                {%endfor%}
                <div class="form-group">
                    <button class="btn  btn-success" id="">Submit Answer</button>
                </div>
                <div class="paginetor">
                  <div class="form-group">
                    {%  if questions.has_next %}
                    <a href="?page={{ questions.next_page_number }}"><button class="btn form-control btn-primary" id="save_ans">Next</button></a>
                  {% else %}
                   <a href="{% url 'quiz:quiz_result' %}"><button class="btn form-control btn-success" id="save_ans">Submit Quiz</button></a>  
                  {% endif %} 
                  </div>
                 </div>  
    </div>
    <script>
        window.onload = initall;
var  saveBookButton ;
function initall() {
    saveBookButton=document.getElementById('save_ans')
    saveBookButton.onclick = save_ans;
}
function save_ans() {
    var ans = $("input:radio[name=name]:checked").val()
    console.log(ans);
    alert("answer submited go next")
    var url = '/quiz/save_ans?ans='+ans
    var req = new XMLHttpRequest();
    req.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
     alert(req.responseText)
    }
  };
  req.open("GET", url, true);
  req.send();
}
    </script>
{% endblock %}

templates/mainsite/quiz/quiz_exam.html
{% extends 'mainsite/base.html' %}
{% load static %}

{% block content %}
<!-- Start Page Title Area -->
<div class="page-title">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <h3>QUIZ</h3>
            </div>
        </div>
    </div>
</div>
    <div class="mt-5 text-center"><h1>Question {{ questions.end_index }} of  {{count}}</h1></div>
    <div class="col-lg-8 border border-success p-4 m-4 mx-auto">
        <form action="{% url 'quiz:save_ans' %}" method="POST"  id="quiz-submit-ajax">
            {% csrf_token %}
            <input type="hidden"  name="user" id="id_user" value="{{ request.user.id }}">
            <input type="hidden"  name="quiz" id="id_quiz" value="{{ id }}">
                
            {% for i in questions%}
                <input type="hidden"  name="question"  id="id_question" value="{{ i.id }}">

                <h1 class="text-center m-4">{{i.question}} </h1>

                    <div class="radio">
                    <label><input class="mr-3" type="radio" name="ans"  id="id_ans" value="choice_one">{{i.choice_one}} </label> 
                    </div>
                    <div class="radio">
                    <label > <input class="mr-3" type="radio" name="ans"  id="id_ans" value="choice_two">{{i.choice_two}}</label>
                  </div>
                  <div class="radio">
                    <label ><input class="mr-3" type="radio" name="ans" id="id_ans" value="choice_three">{{i.choice_three}}</label>
                  </div>
                    <div class="radio">
                    <label ><input class="mr-3" type="radio" name="ans"  id="id_ans" value="choice_four">{{i.choice_four}} </label>
                </div>
            
                {%endfor%}

                <!-- {{ QuizExamForm.as_p }} -->
                <div class="form-group">
                    <input type="submit" value="Submit" class="cng btn btn-success">
                </div>
            </form>
                <div class="paginetor">
                  <div class="form-group">
                    {%  if questions.has_next %}
                    <a href="?page={{ questions.next_page_number }}"><button class="btn form-control btn-primary" id="save_ans">Next</button></a>
                  {% else %}
                   <a href="{% url 'quiz:quiz_result' id %}"><button class="btn form-control btn-success" id="save_ans">Check Result</button></a>  
                  {% endif %} 
                  </div>
                 </div>  
    </div>


{% endblock %}

templates/mainsite/quiz/result.html
{% extends 'mainsite/base.html' %}
{% load static %}

{% block content %}
<!-- Start Page Title Area -->
<div class="page-title">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <h3>Result</h3>
            </div>
        </div>
    </div>
</div>
    <div class="mt-5 text-center"><h1></h1></div>
    <section class="courses-area m-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 pl-0 mb-5">
                    <h3>{{ certificate.course }} </h3>
                </div>
                <div class="col-lg-12 col-md-12 pl-0 mb-5">
                    <h3>Your Score {{score}}:  </h3>
                </div>
                <div class="col-lg-8 col-md-8 pl-0 mb-5">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Question</th>
                            <th>Correct Ans</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in questions %}
                        <tr>   
                            <td>
                                {{i.question}}
                            </td>
                            <td>
                            {% if i.ans == 'choice_one' %} 
                            {{i.choice_one}}
                            {% elif i.ans == 'choice_two' %}
                                {{i.choice_two}}
                            {% elif i.ans == 'choice_three' %}
                                {{i.choice_three}}
                            {% elif i.ans == 'choice_four' %}
                                {{i.choice_four}}
                            {% endif %}
                            </td>
                  
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
                <div class="col-lg-4 col-md-4 pl-0 mb-5">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Your Ans</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in exam_ans %}
                            <tr>   
                                <td>
                                    {% if i.ans == 'choice_one' %} 
                                        {{ i.question.choice_one }}
                                    {% elif i.ans == 'choice_two' %}
                                        {{i.question.choice_two}}
                                    {% elif i.ans == 'choice_three' %}
                                        {{i.question.choice_three}}
                                    {% elif i.ans == 'choice_four' %}
                                        {{i.question.choice_four}}
                                    {% endif %}
                                </td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                    </div>

                    <div class="mt-5">

                        You have successfully completed this course! 
                        <h4 class="buy-cart cart-buttons">
                                
                            <a class="ml-5 " href="{% url 'quiz:certificate' certificate.id %}"><button class="btn btn-danger">Unlock the certificate</button></a>
                                                           
                               
                           </h4>
                        

                    </div>
            </div>
        </div>
    </section>

{% endblock %}

       