billings/urls.py
from django.urls import path
from .views import  CheckoutSuccessView, CheckoutFaildView, InvoiceView



app_name = "billing"


urlpatterns = [

    
    path('success/', CheckoutSuccessView.as_view(), name='success'),
    path('invoice/<slug:tran_id>', InvoiceView.as_view(), name='invoice'),
    path('faild/', CheckoutFaildView.as_view(), name='faild'),

]

carts/urls.py
from django.urls import path
from .views import  CartView, CheckoutView, cart_home, cart_update, cart_detail_api



app_name = "cart"


urlpatterns = [

    
    path('', cart_home, name='cart'),
    path('checkout/<int:id>/', CheckoutView.as_view(), name='checkout'),
    path('update/', cart_update, name='cart-update'),
    path('api/cart/', cart_detail_api, name='api-cart'),

]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('coresite.urls')),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('carts/', include('carts.urls')),
    path('payment/', include('billings.urls')),
    path('mycourses/', include('enrolls.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', include('customadmin.urls')),
    path('quiz/', include('quizapp.urls')),
    path('superadmin/', admin.site.urls),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'coresite.views.handler404'
handler500 = 'coresite.views.handler500'

admin.site.site_header = "GainSkill Super Admin"
admin.site.site_title = "GainSkill"
admin.site.index_title = "Welcome to GainSkill"

carts/models.py
from decimal import Decimal
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed


from courses.models import Course


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if cart_obj.user is None and request.user.is_authenticated:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            try:
                cart_obj = Cart.objects.create(user=request.user)
            except:
                cart_obj = Cart.objects.create(user=None)

            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj



class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.DO_NOTHING)
    products    = models.ManyToManyField(Course, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=65, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=65, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for product in products:
            if product.price is not None or product.offer_price is not None:
                if product.offer_price:
                    total += product.offer_price
                else:
                    total += product.price
                
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()
m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) #* Decimal(1) # 8% tax
    else:
        instance.total = 0.00
pre_save.connect(pre_save_cart_receiver, sender=Cart)

 

carts/forms.py
from django import forms



from billings.models import Billing


class BillingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BillingForm, self).__init__(*args, **kwargs)

        self.fields['full_name'].widget.attrs.update(
            {
                'placeholder': 'Enter First Name',
            }
        )

        for field in self.fields:
            self.fields[field].required = True

        # self.fields['password1'].error_messages.update({
        #     'required': 'Password is required'
        # })


    class Meta:
        model = Billing
        # fields = ['email', 'username', 'first_name',
        #           'last_name',  'password1', 'password2', ]

        exclude = ('user', 'timestamp', 'products')         

carts/views.py
from django.contrib import messages, auth
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.views.generic import CreateView, DetailView, RedirectView, View, ListView, TemplateView, FormView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse

from courses.models import Course
from .models import Cart
from .forms import BillingForm
from .sslcommerz import sslcommerz_payment_gateway


class CartView(ListView):
    model = Cart
    template_name = "mainsite/carts/cart.html"

    def get_queryset(self):
        return self.model.objects.new_or_get(self.request)



def cart_detail_api(request):
    """cart api for refresh cart items on CartView via ajax call"""
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
            "id": x.id,
            "url": x.get_absolute_url(),
            "name": x.title, 
            "price": x.price
            } 
            for x in cart_obj.products.all()]
    cart_data  = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return JsonResponse(cart_data)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = cart_obj.products.all()
    total = 0

    for product in products:
        if product.price is not None or product.offer_price is not None:
            total += product.price
            cart_obj.total = total
    cart_obj.save()

    context = {
        'cart': cart_obj

    }
    return render(request, "mainsite/carts/cart.html", context)


def cart_update(request):

    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Course.objects.get(id=product_id)

        except Product.DoesNotExist:
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
            # messages.success(request, 'Item Was Removed From Cart')
        else:
            cart_obj.products.add(product_obj)
            added = True
            # messages.success(request, 'Item Was Added On Cart')

        request.session['cart_items'] = cart_obj.products.count()

        if request.is_ajax(): # Asynchronous JavaScript And XML / JSON
            json_data = {
                "added": added,
                "removed": not added,
                "CartItemCount": cart_obj.products.count()
            }
            return JsonResponse(json_data)
    return redirect("cart:cart")






class CheckoutView(View):
    """
        Provides the ability to checkout if user is authenticated
    """
    form_class = BillingForm
    template_name = 'mainsite/carts/checkout.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_cart_item(self):
        return get_object_or_404(Cart, id=self.kwargs['id'])


    def get(self, request, *args, **kwargs):
        form = self.form_class()

        context = {

            'form': form,
            'cart': self.get_cart_item()
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            cart = self.get_cart_item()
            # cart_total = self.get_cart_item().total
            try:
                is_save_billing = request.POST['is_save_billing']
            except:
                is_save_billing = False

            user = Cart.objects.filter(user=request.user).values('user')
            if user:
                if is_save_billing:

                        billing = form.save(commit=False)
                        billing.user = request.user
                        billing.save()
                        return redirect(sslcommerz_payment_gateway(form, cart, request.user))
                else:
                    return redirect(sslcommerz_payment_gateway(form, cart, request.user))

        context = {

            'form': form,
            'cart': self.get_cart_item()
        }
        return render(request, self.template_name, context)




    

templates/mainsite/carts/cart.html
{% extends 'mainsite/base.html' %}
{% load static %}


{% block content %}
        
        <!-- Start Page Title Area -->
        <div class="page-title">
            <div class="d-table">
                <div class="d-table-cell">
                    <div class="container">
                        <h3>Cart</h3>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Page Title Area -->
        
        <!-- Start Cart Area -->
        <section class="cart-area ptb-100">
            <div class="container">
            
                    <div class="row table-ajax-refresh">

                        {% if cart.products.count > 0 %}
                        <div class="col-lg-12 col-md-12">
                            <div class="cart-table table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <!-- <th scope="col">Product</th> -->
                                            <th scope="col">No</th>
                                            <th scope="col">Course Name</th>
                    
                                            <th scope="col">Total</th>
                                            <th scope="col">Sub Total</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody class="table-body-ajax-refresh">
                                        {% for course in cart.products.all %}
                                        <tr class="cart-product">
<!--                                             <td class="product-thumbnail">
                                                <a href="#"><img src="assets/img/shop1.jpg" alt="shop"></a>
                                            </td> -->
                                            <td>{{ forloop.counter }}</td>
                                            <td class="text-left"><a href="{{ course.get_absolute_url }}">{{ course.title }}</a></td>
                                            {% if course.offer_price %}
                                            <td>{{ course.offer_price }} {{ site_data.currency }} </td>
                                            {% elif course.price  %}
                                            <td>{{ course.price }} {{ site_data.currency }} </td>
                                            {% else %}
                                            <td>Free</td>
                                            {% endif %}
                                            {% if course.offer_price %}
                                            <td>{{ course.offer_price }} {{ site_data.currency }} </td>
                                            {% elif course.price  %}
                                            <td>{{ course.price }} {{ site_data.currency }} </td>
                                            {% else %}
                                            <td>Free</td>
                                            {% endif %}
                                            <td class="course-remove-ajax">
                                                <form method='POST' class="course-ajax" action='{% url "cart:cart-update" %}'> 
                                                    {% csrf_token %}
                                                    <input class="cart-item-product-id" type='hidden' name='product_id' value='{{ course.id }}' />
                                                    <div class="cart-buttons"><button class="btn btn-primary ccx"><i class="icofont-close"></i></button></div>
                                                </form>
                                            </td>    
                                        </tr>

                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        
                        <div class="col-lg-8 col-md-12">
                            <!-- <div class="cart-buttons">
                                <button type="submit" class="btn btn-primary">Update Cart</button>
                                <a href="#" class="btn btn-primary">Continue Shopping</a>
                            </div>
                            
                            <div class="cart-coupon">
                                <h4>Coupon</h4>
                                <p>Enter your coupon code if you have one.</p>
                                <div class="cuppon-form">
                                    <input type="text" class="form-control" placeholder="Coupon Code">
                                    <button type="submit" class="btn btn-primary">Apply Coupon</button>
                                </div>
                            </div> -->
                        </div>
                        
                        <div class="col-lg-4 col-md-12">
                            <div class="cart-total">
                                <h3>Cart Totals</h3>
                                
                                <div class="cart-total-table table-responsive">
                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                <td>Subtotal</td>
                                                <td class="sub-amount">{{ cart.subtotal }} {{ site_data.currency }} </td>
                                            </tr>
                                            <tr>
                                                <td>Total</td>
                                                <td class="total-amount">{{ cart.total }} {{ site_data.currency }} </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="proceed-to-checkout">
                                    <a href="{% url 'cart:checkout' cart.id %}" type="submit" class="btn btn-primary">Proceed To Checkout</a>
                                </div>
                            </div>
                        </div>

                        {% else %}

                        <div class="col-lg-12 col-md-12">
                            Cart Is Empty
                        </div>

                        {% endif %}

                    </div>
           
            </div>
        </section>
        <!-- End Cart Area -->
        
{% endblock %}

templates/mainsite/carts/checkout-faild.html
{% extends 'mainsite/base.html' %}
{% load static %}



{% block content %}


    <!-- Start Page Title Area -->
    <div class="page-title">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <h3>Checkout</h3>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page Title Area -->


    <!-- Start Checkout Area -->
    <section class="checkout-area ptb-100">
        <div class="container">
                <h1>Payment Was Unsuccessful </h1>
        </div>
    </section>
    <!-- End Checkout Area -->

{% endblock %}

templates/mainsite/carts/checkout-success.html
{% extends 'mainsite/base.html' %}
{% load static %}



{% block content %}


    <!-- Start Page Title Area -->
    <div class="page-title">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <h3>Payment Status</h3>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page Title Area -->


    <!-- Start Checkout Area -->
    <section class="checkout-area ptb-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="about-text">
                        <h3>Your Payment was <span>Successful</span></h3>
                        <h4 class="">Your Transaction id: {{ transaction.tran_id }}</h4>
                        <h5 class="p-5">Save Your Invoice <a href="{% url 'billing:invoice' transaction.tran_id %}" target="_blank" rel="noopener noreferrer"><span style="border-left: olive;">Click Here</span></a></h5>
                    </div>
                </div>
                
                <!-- <div class="col-lg-6 col-md-12">
                    <div class="about-slider">
                        <div class="item" style="height:340px; width:700px;">
                            <img src="{% if about.thumbnail_one %}  {{ about.thumbnail_one.url }} {% endif %}" alt="about">
                        </div>
                        <div class="item" style="height:340px; width:700px;">
                            <img src="{% if about.thumbnail_two %}  {{ about.thumbnail_two.url }} {% endif %}" alt="about">
                        </div>
                        <div class="item" style="height:340px; width:700px;">
                            <img src="{% if about.thumbnail_three %}  {{ about.thumbnail_three.url }} {% endif %}" alt="about">
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-6">
                    <div class="single-about">
                        <i class="icofont-paper-plane"></i>
                        <h3>Progressive Programs</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisi cing elit. Quos dolo rem consequ untur, natus laudantium commodi earum aliquid in ullam.Lorem ipsum.</p>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-6">
                    <div class="single-about">
                        <i class="icofont-checked"></i>
                        <h3>Online Courses</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisi cing elit. Quos dolo rem consequ untur, natus laudantium commodi earum aliquid in ullam.Lorem ipsum.</p>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-6 offset-md-3 offset-lg-0">
                    <div class="single-about">
                        <i class="icofont-airplane-alt"></i>
                        <h3>International Students</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisi cing elit. Quos dolo rem consequ untur, natus laudantium commodi earum aliquid in ullam.Lorem ipsum.</p>
                    </div>
                </div>
                
                <div class="col-lg-6 col-md-6">
                    <div class="about-content">
                        <h3>Who we are?</h3>
                        <p class="mb-0">{{ about.our_mission | safe }}</p>
                    </div>
                </div>
                
                <div class="col-lg-6 col-md-6">
                    <div class="about-content">
                        <h3>Our mission</h3>
                        <p class="mb-0">{{ about.who_we_are | safe }}</p></p>
                    </div>
                </div> -->
            </div>
        </div>
    </section>



{% endblock %}

<h1>Your Payment was Successful</h1>
<h1>Your Transaction id {{ transaction.tran_id }}</h1>
<h1>Print Your Invoice <a href="{% url 'billing:invoice' transaction.tran_id %}" target="_blank" rel="noopener noreferrer">Invoice</a></h1>

templates/mainsite/carts/invoice.html
{% load static %}

{% block content %}

        <style type="text/css">
          
            span.cls_002{font-family:"DejaVu Serif Condensed",serif;font-size:17.3px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
            div.cls_002{font-family:"DejaVu Serif Condensed",serif;font-size:17.3px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
            span.cls_003{font-family:"DejaVu Sans Condensed Bold",serif;font-size:12.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            div.cls_003{font-family:"DejaVu Sans Condensed Bold",serif;font-size:12.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            span.cls_004{font-family:"DejaVu Sans Condensed",serif;font-size:9.8px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
            div.cls_004{font-family:"DejaVu Sans Condensed",serif;font-size:9.8px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
            span.cls_005{font-family:"DejaVu Sans Condensed Bold",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            div.cls_005{font-family:"DejaVu Sans Condensed Bold",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            span.cls_006{font-family:"DejaVu Sans Condensed Bold",serif;font-size:11.3px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            div.cls_006{font-family:"DejaVu Sans Condensed Bold",serif;font-size:11.3px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            span.cls_007{font-family:"DejaVu Sans Condensed",serif;font-size:9.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
            div.cls_007{font-family:"DejaVu Sans Condensed",serif;font-size:9.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
            span.cls_008{font-family:"DejaVu Sans Condensed Bold",serif;font-size:9.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            div.cls_008{font-family:"DejaVu Sans Condensed Bold",serif;font-size:9.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}
            span.cls_009{font-family:"DejaVu Sans Condensed",serif;font-size:11.3px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
            div.cls_009{font-family:"DejaVu Sans Condensed",serif;font-size:11.3px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}
    
        </style>

        <div id="exampl">
        <div style="position: absolute; left: 50%; margin-left: -420px; top: 0px; width: 841px; height: 794px; border-style: outset; overflow: hidden;">
            <div style="position: absolute; left: 0px; top: 0px;">
                <img src="{% static 'assets/img/background1.jpg' %}" width="841" height="1190" />
              
            </div>

            <!-- <div style="position: absolute; left: 360.14px; top: 131.64px;" class="cls_002"><span class="cls_002">Carnival Internet</span></div> -->
              
            <div style="left: 64px; position: relative; top: 154.58px;" class="cls_002"><span class="cls_002">Payment Invoice {{ transaction.tran_id }}</span></div>
            <div style="position: absolute; left: 91.28px; top: 214.96px;" class="cls_003"><span class="cls_003">GainSkill</span></div>
            <div style="position: absolute; left: 91.28px; top: 230.88px;" class="cls_004"><span class="cls_004">BAUST,Saidpur</span></div>
            <div style="position: absolute; left: 91.28px; top: 243.85px;" class="cls_004"><span class="cls_004">Nilphamari,Bangladesh.</span></div>
            <div style="position: absolute; left: 91.28px; top: 268.09px;" class="cls_005"><span class="cls_005">Customer Information:</span></div>
            <!-- <div style="position: absolute; left: 92.03px; top: 287.22px;" class="cls_006"><span class="cls_006">Customer Information:</span></div> -->
            <div style="position: absolute; left: 92.03px; top: 302.15px;" class="cls_007"><span class="cls_007">{{ transaction.user.get_full_name }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 338.06px;" class="cls_007"><span class="cls_007">Email: {{ transaction.user.email }}</span></div>
            <div style="position: absolute; left: 91.28px; top: 406.65px;" class="cls_005"><span class="cls_005">Payment Information</span></div>
            <div style="position: absolute; left: 92.03px; top: 425.78px;" class="cls_006"><span class="cls_006">Payment Method:</span></div>
            <div style="position: absolute; left: 333.23px; top: 428.78px;" class="cls_006"><span class="cls_006">Items Ordered</span></div>
            <div style="position: absolute; left: 734.67px; top: 428.78px;" class="cls_006"><span class="cls_006">Price</span></div>
            <div style="position: absolute; left: 92.03px; top: 440.71px;" class="cls_007"><span class="cls_007">Transaction Type : </span><span class="cls_008">Online</span></div>
            <!-- <div style="position: absolute; left: 333.23px; top: 443.74px;" class="cls_006"><span class="cls_006">{{ transaction.user.email  }}</span></div> -->
            <div style="position: absolute; left: 703.88px; top: 443.74px;" class="cls_009"><span class="cls_009">{{ transaction.currency }} {{ transaction.store_amount }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 452.68px;" class="cls_007"><span class="cls_007">Card Type : {{ transaction.card_type }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 464.65px;" class="cls_007"><span class="cls_007">Card Number: {{ transaction.card_issuer }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 476.62px;" class="cls_007"><span class="cls_007">Bank Authorize Id: {{ transaction.bank_tran_id }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 488.59px;" class="cls_007"><span class="cls_007">Card Holder's Name/Account :</span></div>
            <div style="position: absolute; left: 544.61px; top: 489.45px;" class="cls_009"><span class="cls_009">Item(s) Subtotal:</span></div>
            <div style="position: absolute; left: 703.88px; top: 489.45px;" class="cls_009"><span class="cls_009">{{ transaction.currency }} {{ transaction.store_amount }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 500.56px;" class="cls_007"><span class="cls_007">IP Address: 103.106.239.46.[Bangladesh.]</span></div>
            <div style="position: absolute; left: 522.86px; top: 504.41px;" class="cls_009"><span class="cls_009">Shipping & Handling:</span></div>
            <div style="position: absolute; left: 716.75px; top: 504.41px;" class="cls_009"><span class="cls_009">{{ transaction.currency }} 0.00</span></div>
            <div style="position: absolute; left: 92.03px; top: 512.53px;" class="cls_007"><span class="cls_007">Gateway Currency: {{ transaction.currency }}</span></div>
            <div style="position: absolute; left: 748.78px; top: 519.37px;" class="cls_009"><span class="cls_009">----</span></div>
            <div style="position: absolute; left: 92.03px; top: 524.5px;" class="cls_007"><span class="cls_007">{{ transaction.currency }} Amount: {{ transaction.store_amount }} Taka</span></div>
            <div style="position: absolute; left: 558.71px; top: 534.34px;" class="cls_006"><span class="cls_006">Grand Total:</span></div>
            <div style="position: absolute; left: 697.8px; top: 534.34px;" class="cls_006"><span class="cls_006">{{ transaction.currency }} {{ transaction.store_amount }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 565.76px;" class="cls_006"><span class="cls_006">Billing Information :</span></div>
            <div style="position: absolute; left: 92.03px; top: 580.69px;" class="cls_007"><span class="cls_007">{{ transaction.user.get_full_name }}</span></div>
            <div style="position: absolute; left: 92.03px; top: 604.63px;" class="cls_007"><span class="cls_007">Phone: 01751006793</span></div>
            <div style="position: absolute; left: 92.03px; top: 616.6px;" class="cls_007"><span class="cls_007">Email: {{ transaction.user.email }}</span></div>
            <div style="position: absolute; left: 91.28px; top: 651.48px;" class="cls_006"><span class="cls_006">if any Questions? Email: operation@gainskill.xyz</span></div>
        </div>
        <img style="
            position: relative;
            left: 436px;
            top: 232px;
            opacity: 0.3;
            height: 607px;
       " src="{% static 'assets/img/PAID-1.png' %}"  />
    </div>
    <div style="
    position: relative;
    text-align: right;
    margin: 0 40px;
    top:-500px
">
    <button class="myButton" OnClick="CallPrint(this.value)">PRINT</button>
    <br>
 <a style="width: 77px;height: 26px;" class="myButton"  href="{% static 'assets/pdf/inv.pdf' %}">DOWNLOAD</a>
    
</div>

    </section>

    
    <script>
        function CallPrint(strid) {
            var prtContent = document.getElementById("exampl");
            var WinPrint = window.open('', '', 'left=0,top=0,width=794px,height=794px,toolbar=0,scrollbars=0,status=0');
            WinPrint.document.write(prtContent.innerHTML);
            WinPrint.document.close();
            WinPrint.focus();
            WinPrint.print();
            WinPrint.close();
        }

    </script>

    
<style>
    .myButton {
        box-shadow: 0px 10px 14px -7px #3e7327;
        background:linear-gradient(to bottom, #77b55a 5%, #72b352 100%);
        background-color:#77b55a;
        border-radius:4px;
        border:1px solid #4b8f29;
        display:inline-block;
        cursor:pointer;
        color:#ffffff;
        font-family:Arial;
        font-size:13px;
        font-weight:bold;
        padding:6px 12px;
        text-decoration:none;
        text-shadow:0px 1px 0px #5b8a3c;
        width: 102px;
        height: 39px;
    }
    .myButton:hover {
        background:linear-gradient(to bottom, #72b352 5%, #77b55a 100%);
        background-color:#72b352;
    }
    .myButton:active {
        position:relative;
        top:1px;
    }
    
            
    
    </style>
{% endblock %}