accounts/urls.py
from django.urls import path, include


from .views import InstructorRegisterView, ProfileView, LogInView, LogoutView, StudentRegisterView,EditProfileView, SettingView , ChangePassword


app_name = "accounts"

urlpatterns = [
    
    path('login/', LogInView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/<int:id>/', ProfileView.as_view(), name="profile"),
    path('student/register/', StudentRegisterView.as_view(), name="student-register"),
    path('instructor/register/', InstructorRegisterView.as_view(), name="instructor-register"),
    path('settings/', SettingView.as_view() ,name="setting"),
    path('profile/update/',EditProfileView ,name="profile-update"),
    path('password/', ChangePassword, name='change_password'),

    
 
    
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('coresite.urls')),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('carts/', include('carts.urls')),
    path('payment/', include('billings.urls')),
    path('mycourses/', include('enrolls.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', include('customadmin.urls')),
    path('quiz/', include('quizapp.urls')),
    path('superadmin/', admin.site.urls),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'coresite.views.handler404'
handler500 = 'coresite.views.handler500'

admin.site.site_header = "GainSkill Super Admin"
admin.site.site_title = "GainSkill"
admin.site.index_title = "Welcome to GainSkill"

customadmin/urls.py
from django.urls import include, path
from django.views.generic import RedirectView

from .views import *


app_name = "customadmin"

urlpatterns = [

    
    path('', RedirectView.as_view(url='dashboard/')),
    path('dashboard/', DashBoardView.as_view(), name="dashboard"),
    path('users/', AllUsersView.as_view(), name="users"),
    path('instructors/', AllInstructorsView.as_view(), name="instructors"),
    path('students/', AllStudentsView.as_view(), name="students"),
    path('courses/', CoursesView.as_view(), name="courses"),
    path('profile/<int:pk>', ProfileView.as_view(), name="profile"),
    path('courses/', CoursesView.as_view(), name="all-courses"),
    path('newcourses/', NewCoursesView.as_view(), name="new-courses"),  
    path('categories/', CategoryView.as_view(), name="categories"),
    path('create/category/', CreateCategoryView.as_view(), name="new-category"),
    path('course/<slug:slug>/', CourseDetailView.as_view(), name="single-course"),
    path('approvedorreject/', approvedOrReject, name="approvedorreject"),
    path('testimonial/', TestimonialView.as_view(), name="testimonial"),
    path('testimonial/add/', CreateTestimonialView.as_view(), name="add-testimonial"),

    path('settings/', include([
            path('gateway/update/',  PaymentGatewaySettingsView.as_view(), name="gateway-settings"),
            path('general/update/', FrontEndSettings.as_view(), name="frontend-settings"),
            path('about/update/', AboutView.as_view(), name="about"),
    ])),


]

templates/adminsection/includes/_footer.html
<!-- Footer -->


<footer class="main-footer">
    <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0-pre
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

templates/adminsection/includes/_head.html
{% load static %}


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />


    <link rel="shortcut icon" href="images/favicon_1.ico">

    

    <!-- Base Css Files -->
    <link href="{% static 'customadmin/css/bootstrap.min.css' %}" rel='stylesheet' />

    <!-- Font Icons -->
    <!-- <link href="{% static 'customadmin/assets/font-awesome/css/font-awesome.min.css' %}" rel='stylesheet' /> -->
    <!-- <link href="{% static 'customadmin/assets/ionicon/css/ionicons.min.css' %}" rel='stylesheet' /> -->
    <link href="{% static 'customadmin/css/material-design-iconic-font.min.css' %}" rel='stylesheet'>

    <!-- animate css -->
    <link href="{% static 'customadmin/css/animate.css' %}" rel='stylesheet' />

    <!-- Waves-effect -->
    <link href="{% static 'customadmin/css/waves-effect.css' %}" rel='stylesheet'>

    <!-- sweet alerts -->
    <link href="{% static 'customadmin/assets/sweet-alert/sweet-alert.min.css' %}" rel='stylesheet'>

    <!-- Custom Files -->
    <link href="{% static 'customadmin/css/helper.css' %}" rel='stylesheet' type='text/css' />
    <link href="{% static 'customadmin/css/style.css'%}" rel='stylesheet' type='text/css' />

    <script src="{% static 'customadmin/js/modernizr.min.js' %}"></script>

templates/adminsection/includes/_header.html
{% load static %} 
 <!-- Top Bar Start -->
            <div class="topbar">
              <!-- LOGO -->
              <div class="topbar-left">
                  <div class="text-center">
                      <a href="/" class="logo"><i class="md md-terrain"></i> <span>GainSkill </span></a>
                  </div>
              </div>
              <!-- Button mobile view to collapse sidebar menu -->
              <div class="navbar navbar-default" role="navigation">
                  <div class="container">
                      <div class="">
                          <div class="pull-left">
                              <button class="button-menu-mobile open-left">
                                  <i class="fa fa-bars"></i>
                              </button>
                              <span class="clearfix"></span>
                          </div>
                          <form class="navbar-form pull-left" role="search">
                              <div class="form-group">
                                  <input type="text" class="form-control search-bar" placeholder="Type here for search...">
                              </div>
                              <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                          </form>

                          <ul class="nav navbar-nav navbar-right pull-right">
                              <li class="dropdown hidden-xs">
                                  <a href="#" data-target="#" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                                      <i class="md md-notifications"></i> <span class="badge badge-xs badge-danger">3</span>
                                  </a>
                                  <ul class="dropdown-menu dropdown-menu-lg">
                                      <li class="text-center notifi-title">Notification</li>
                                      <li class="list-group">
                                         <!-- list item-->
                                         <a href="javascript:void(0);" class="list-group-item">
                                            <div class="media">
                                               <div class="pull-left">
                                                  <em class="fa fa-user-plus fa-2x text-info"></em>
                                               </div>
                                               <div class="media-body clearfix">
                                                  <div class="media-heading">New user registered</div>
                                                  <p class="m-0">
                                                     <small>You have 10 unread messages</small>
                                                  </p>
                                               </div>
                                            </div>
                                         </a>
                                         <!-- list item-->
                                          <a href="javascript:void(0);" class="list-group-item">
                                            <div class="media">
                                               <div class="pull-left">
                                                  <em class="fa fa-diamond fa-2x text-primary"></em>
                                               </div>
                                               <div class="media-body clearfix">
                                                  <div class="media-heading">New settings</div>
                                                  <p class="m-0">
                                                     <small>There are new settings available</small>
                                                  </p>
                                               </div>
                                            </div>
                                          </a>
                                          <!-- list item-->
                                          <a href="javascript:void(0);" class="list-group-item">
                                            <div class="media">
                                               <div class="pull-left">
                                                  <em class="fa fa-bell-o fa-2x text-danger"></em>
                                               </div>
                                               <div class="media-body clearfix">
                                                  <div class="media-heading">Updates</div>
                                                  <p class="m-0">
                                                     <small>There are
                                                        <span class="text-primary">2</span> new updates available</small>
                                                  </p>
                                               </div>
                                            </div>
                                          </a>
                                         <!-- last list item -->
                                          <a href="javascript:void(0);" class="list-group-item">
                                            <small>See all notifications</small>
                                          </a>
                                      </li>
                                  </ul>
                              </li>
                              <li class="hidden-xs">
                                  <a href="#" id="btn-fullscreen" class="waves-effect waves-light"><i class="md md-crop-free"></i></a>
                              </li>
                              <li class="hidden-xs">
                                  <a href="#" class="right-bar-toggle waves-effect waves-light"><i class="md md-chat"></i></a>
                              </li>
                              <li class="dropdown">
                                  <a href="" class="dropdown-toggle profile" data-toggle="dropdown" aria-expanded="true"><img src="{% if request.user.profile.profile_pic %}  {{ request.user.profile.profile_pic.url }} {% endif %}" alt="user-img" class="img-circle"> </a>
                                  <ul class="dropdown-menu">
                                      <li><a href="javascript:void(0)"><i class="md md-face-unlock"></i> Profile</a></li>
                                      <li><a href="javascript:void(0)"><i class="md md-settings"></i> Settings</a></li>
                                      <li><a href="javascript:void(0)"><i class="md md-lock"></i> Lock screen</a></li>
                                      <li><a href="javascript:void(0)"><i class="md md-settings-power"></i> Logout</a></li>
                                  </ul>
                              </li>
                          </ul>
                      </div>
                      <!--/.nav-collapse -->
                  </div>
              </div>
          </div>
          <!-- Top Bar End -->

templates/adminsection/includes/_notification.html
{% if messages %}
{% for message in messages %}
<!-- <div class="mb-5 alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div> -->

<!-- <div class="jsdemo-notification-button">
    <div class="">
        <button type="button" class="btn bg-indigo btn-block waves-effect" data-placement-from="top" data-placement-align="right"
                data-animate-enter="animated lightSpeedIn" data-animate-exit="animated lightSpeedOut"
                data-color-name="bg-black">
            LIGHT SPEED IN/OUT
        </button>
    </div>
</div> -->


<!-- 
    <div data-notify="container" 
    class="alert  {{ message.tags }}  alert-dismissible 
    animated lightSpeedIn" 
    style="display: inline-block; 
    margin: 0px auto; position: fixed;  z-index: 1031; top: 70px; right: 20px;">
    <button type="button" aria-hidden="true" class="close" 
    data-notify="dismiss" style="position: absolute; right: 10px; top: 5px; z-index: 1033;">×</button>
    <span data-notify="icon"></span>
    <span data-notify="message">{{ message }}</span>
    <a href="#" target="_blank" data-notify="url"></a></div> -->


<!-- <div id="notification-alert" class="mb-5 alert {{ message.tags }} alert-dismissible animated lightSpeedIn" style="display: inline-block; 
    margin: 0px auto; position: fixed;  z-index: 1031; top: 70px; right: 20px;" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div> -->



<script type="text/javascript">
   

jQuery(document).ready(function() {
toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut",
        "hideMethod": "fadeOut"
      }

   toastr.{{ message.tags }}('{{ message }}');

  });



</script>
{% endfor %}
{% endif %}

templates/adminsection/includes/_scripts.html
{% load static %}        
<script>
  var resizefunc = [];
</script>
<script type="text/javascript">
  /* ==============================================
  Counter Up
  =============================================== */
  jQuery(document).ready(function($) {
      $('.counter').counterUp({
          delay: 100,
          time: 1200
      });
  });
</script>

<!-- jQuery  -->
<script src="{% static 'customadmin/js/jquery.min.js' %}"></script>
<script src="{% static 'customadmin/js/bootstrap.min.js' %}"></script>
<!-- <script src="{% static 'customadmin/js/waves.js' %}"></script> -->
<script src="{% static 'customadmin/js/wow.min.js' %}"></script>
<script src="{% static 'customadmin/js/jquery.nicescroll.js' %}" type='text/javascript'></script>
<script src="{% static 'customadmin/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'customadmin/assets/chat/moment-2.2.1.js' %}"></script>
<script src="{% static 'customadmin/assets/jquery-sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'customadmin/assets/jquery-detectmobile/detect.js' %}"></script>
<script src="{% static 'customadmin/assets/fastclick/fastclick.js' %}"></script>
<script src="{% static 'customadmin/assets/jquery-slimscroll/jquery.slimscroll.js' %}"></script>
<script src="{% static 'customadmin/assets/jquery-blockui/jquery.blockUI.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<!-- sweet alerts -->
<script src="{% static 'customadmin/assets/sweet-alert/sweet-alert.min.js' %}"></script>
<script src="{% static 'customadmin/assets/sweet-alert/sweet-alert.init.js' %}"></script>

<!-- flot Chart -->
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.js' %}"></script>
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.time.js' %}"></script>
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.resize.js' %}"></script>
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.pie.js' %}"></script>
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.selection.js' %}"></script>
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.stack.js' %}"></script>
<script src="{% static 'customadmin/assets/flot-chart/jquery.flot.crosshair.js' %}"></script>

<!-- Counter-up -->
<script src="{% static 'customadmin/assets/counterup/waypoints.min.js' %}" type='text/javascript'></script>
<script src="{% static 'customadmin/assets/counterup/jquery.counterup.min.js' %}" type='text/javascript'></script>

<!-- CUSTOM JS -->
<script src="{% static 'customadmin/js/jquery.app.js' %}"></script>

<!-- Dashboard -->
<script src="{% static 'customadmin/js/jquery.dashboard.js' %}"></script>

<!-- Chat -->
<script src="{% static 'customadmin/js/jquery.chat.js' %}"></script>

<!-- Todo -->
<script src="{% static 'customadmin/js/jquery.todo.js' %}"></script>

templates/adminsection/includes/_sidebar.html
<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <div class="user-details">
            <div class="pull-left">
                <img src="{% if request.user.profile.profile_pic %}  {{ request.user.profile.profile_pic.url }} {% endif %}" alt="" class="thumb-md img-circle">
            </div>
            <div class="user-info">
                <div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">{{ request.user.username | upper  }} <span
                            class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="javascript:void(0)"><i class="md md-face-unlock"></i> Profile<div
                                    class="ripple-wrapper"></div></a></li>
                        <li><a href="javascript:void(0)"><i class="md md-settings"></i> Settings</a></li>
                        <li><a href="{% url 'accounts:logout' %}"><i class="md md-settings-power"></i> Logout</a></li>
                    </ul>
                </div>

                <p class="text-muted m-0">Administrator</p>
            </div>
        </div>
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li>
                    <a href="{% url 'customadmin:dashboard' %}"
                        class="waves-effect {% if 'dashboard' in request.path %} active {% endif %}"><i
                            class="md md-home"></i><span> Dashboard </span></a>
                </li>

                <li class="has_sub">
                    <a href="#"
                        class="waves-effect {% if 'users' in request.path or 'instructors' in request.path or 'students' in request.path %} active {% endif %} "><i
                            class="md md-mail"></i><span>Manage Users </span><span class="pull-right"><i
                                class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li {% if 'users' in request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:users' %}"><i class="md md-forward"></i>All Users</a></li>
                        <li {% if 'instructors' in request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:instructors' %}"><i class="md md-forward"></i>All
                                Instructors</a></li>
                        <li {% if 'students' in request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:students' %}"><i class="md md-forward"></i>All Students</a>
                        </li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="#"
                        class="waves-effect {% if 'courses' in request.path or 'new-courses' in request.path %} active {% endif %}"><i
                            class="md md-mail"></i><span>Manage Courses </span><span class="pull-right"><i
                                class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li {% if '/admin/courses/' == request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:all-courses' %}"><i class="md md-forward"></i>All Courses</a>
                        </li>
                        <li {% if 'newcourses' in request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:new-courses' %}"><i class="md md-forward"></i>Pending
                                Courses</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="#"
                        class="waves-effect {% if 'categories' in request.path %} active {% endif %}"><i
                            class="md md-mail"></i><span>Manage Categories </span><span class="pull-right"><i
                                class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li {% if '/admin/categories/' == request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:categories' %}"><i class="md md-forward"></i>All Categories</a>
                        </li>
                        <li {% if 'newcourses' in request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:new-courses' %}"><i class="md md-forward"></i>Sub Categories</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="#"
                        class="waves-effect {% if 'general' in request.path or 'gateway' in request.path or 'about' in request.path %} active {% endif %}"><i
                            class="md md-now-widgets"></i><span>Settings </span><span class="pull-right"><i
                                class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li {% if 'general' in request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:frontend-settings' %}"><i class="md md-forward"></i>General
                                Settings</a></li>
                        <li {% if 'gateway' in request.path %} class="active" {% endif %}><a
                                href="{% url 'customadmin:gateway-settings' %}"><i class="md md-forward"></i>Payment
                                Gateway</a>
                        </li>
                        <li {% if 'about' in request.path %} class="active" {% endif %}><a
                            href="{% url 'customadmin:about' %}"><i class="md md-forward"></i>About Page
                    </li>
                    </ul>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->